server:
  port: 8083
spring:
  application:
    name: spring-boot-app
  data:
    mongodb:
      uri: ${CONFIG_MONGODB_SERVER}
      username: ${CONFIG_MONGODB_ADMINUSERNAME}
      password: ${CONFIG_MONGODB_ADMINPASSWORD}
      database: test
